apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-simple-python-web-server-
  namespace: py-14-dev
  labels:
    backstage.io/kubernetes-id:  py-14
    type: pipeline
spec:
  params:
    - name: deployment-namex
      value: python-web-server
    - name: git-url
      value: 'https://gitlab-gitlab.apps.cluster-mcr9m.sandbox906.opentlc.com/development/py-14.git'
    - name: git-revision
      value: master
    - name: IMAGE
      value: >-
        quay-mcr9m.apps.cluster-mcr9m.sandbox906.opentlc.com/quayadmin/py-14
  pipelineRef:
    name: build-and-deploy
  serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
        status: {}
    - name: docker-config
      secret:
        secretName: py-14-registry-creds